before_script:
- export PATH=$PATH:$HOME/.local/bin/
- pip install --user manu343726-conan-tools
- pip install --user --upgrade conan
- conan --version
- conan remote add Manu343726 https://api.bintray.com/conan/manu343726/conan-packages
- conan remote add bincrafters  https://api.bintray.com/conan/bincrafters/public-conan
- conan profile new --detect default
- if [[ ! -z "$manu343726_bintray_key" ]]; then echo remote password variable "manu343726_bintray_key"
  not empty, ok; else echo remote password variable "manu343726_bintray_key" empty,
  error && exit 1; fi
- conan user Manu343726 -p $manu343726_bintray_key -r Manu343726
build_clang_6.0.0_clang60_build_type=Release+shared=False:
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False -o clang:shared=False clang
    clang/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload clang/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_6.0.0_gcc5_build_type=Release+shared=False:
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False -o clang:shared=False clang
    clang/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload clang/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_6.0.0_gcc7_build_type=Release+shared=False:
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False -o clang:shared=False clang
    clang/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload clang/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_6.0.0_gcc8_build_type=Release+shared=False:
  image: lasote/conangcc8
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False -o clang:shared=False clang
    clang/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload clang/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_conan_tools/0.3@Manu343726/testing:
  image: lasote/conangcc5
  script:
  - export RECIPE_DIR=`manu343726-conan-tools generate_python_package clang_conan_tools
    0.3 Manu343726 testing --with-test --url "https://gitlab.com/Manu343726/clang-conan-packages"`
  - cat -n $RECIPE_DIR/conanfile.py
  - cat -n $RECIPE_DIR/test_package/conanfile.py
  - conan create $RECIPE_DIR Manu343726/testing
  - conan upload clang_conan_tools/0.3@Manu343726/testing --all --force --retry 3
    -r Manu343726
  stage: common-recipe-scripts
  tags:
  - linux
  - docker
build_compiler-rt_6.0.0_clang60_build_type=Release+shared=False:
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False compiler-rt compiler-rt/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/6.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_6.0.0_gcc5_build_type=Release+shared=False:
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False compiler-rt compiler-rt/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/6.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_6.0.0_gcc7_build_type=Release+shared=False:
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False compiler-rt compiler-rt/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/6.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_6.0.0_gcc8_build_type=Release+shared=False:
  image: lasote/conangcc8
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False compiler-rt compiler-rt/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/6.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_libcxx_6.0.0_clang60_build_type=Release+shared=False:
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False libcxx libcxx/6.0.0@Manu343726/testing
    --build=missing
  - conan remove -b -s -f "*"
  - conan upload libcxx/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_6.0.0_gcc5_build_type=Release+shared=False:
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False libcxx libcxx/6.0.0@Manu343726/testing
    --build=missing
  - conan remove -b -s -f "*"
  - conan upload libcxx/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_6.0.0_gcc7_build_type=Release+shared=False:
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False libcxx libcxx/6.0.0@Manu343726/testing
    --build=missing
  - conan remove -b -s -f "*"
  - conan upload libcxx/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_6.0.0_gcc8_build_type=Release+shared=False:
  image: lasote/conangcc8
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    -o compiler-rt:shared=False -o libcxx:shared=False libcxx libcxx/6.0.0@Manu343726/testing
    --build=missing
  - conan remove -b -s -f "*"
  - conan upload libcxx/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_llvm_6.0.0_clang60_build_type=Release+shared=False:
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    llvm llvm/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload llvm/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_6.0.0_gcc5_build_type=Release+shared=False:
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    llvm llvm/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload llvm/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_6.0.0_gcc7_build_type=Release+shared=False:
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    llvm llvm/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload llvm/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_6.0.0_gcc8_build_type=Release+shared=False:
  image: lasote/conangcc8
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=6.0.0 conan create --profile=default -o llvm:shared=False
    llvm llvm/6.0.0@Manu343726/testing --build=missing
  - conan remove -b -s -f "*"
  - conan upload llvm/6.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
deploy-sources-to-bintray:
  image: lasote/conangcc5
  script:
  - ./get_jfrog.sh && ./jfrog bt config --interactive=false --user=Manu343726 --key=$manu343726_bintray_key
    --licenses="MIT"
  - export LLVM_URL=http://releases.llvm.org EXT=.src.tar.xz
  - export COMPONENT=llvm VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  stage: sources
stages:
- common-recipe-scripts
- sources
- llvm
- compiler-rt
- libcxx
- clang
