before_script:
- pip install --user manu343726-conan-tools
- conan --version
- conan remote add Manu343726 https://api.bintray.com/conan/manu343726/conan-packages
- conan profile new --detect default
- conan user Manu343726 -p $manu343726_bintray_key -r Manu343726
build_clang_3.8.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_clang60_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_clang60_build_type=Release+shared=True
  - build_libcxx_3.8.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_3.8.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc5_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_gcc5_build_type=Release+shared=True
  - build_libcxx_3.8.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_3.8.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc7_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_gcc7_build_type=Release+shared=True
  - build_libcxx_3.8.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_4.0.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_clang60_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_clang60_build_type=Release+shared=True
  - build_libcxx_4.0.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_4.0.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc5_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_gcc5_build_type=Release+shared=True
  - build_libcxx_4.0.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_4.0.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc7_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_gcc7_build_type=Release+shared=True
  - build_libcxx_4.0.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True -o clang:shared=True clang Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload clang/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: clang
  tags:
  - linux
  - docker
build_clang_conan_tools/0.2@Manu343726/testing:
  image: lasote/conangcc5
  script:
  - export RECIPE_DIR=`manu343726-conan-tools generate_python_package clang_conan_tools
    0.2 Manu343726 testing --with-test --url "https://gitlab.com/Manu343726/clang-conan-packages"`
  - cat -n $RECIPE_DIR/conanfile.py
  - cat -n $RECIPE_DIR/test_package/conanfile.py
  - conan create $RECIPE_DIR Manu343726/testing
  - conan upload clang_conan_tools/0.2@Manu343726/testing --all --force --retry 3
    -r Manu343726
  stage: common-recipe-scripts
  tags:
  - linux
  - docker
build_compiler-rt_3.8.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/3.8.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_3.8.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/3.8.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_3.8.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/3.8.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_4.0.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/4.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_4.0.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/4.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_compiler-rt_4.0.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True compiler-rt Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload compiler-rt/4.0.0@Manu343726/testing -r Manu343726 --all --force
    --retry 3
  stage: compiler-rt
  tags:
  - linux
  - docker
build_libcxx_3.8.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_clang60_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_3.8.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc5_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_3.8.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_3.8.0_gcc7_build_type=Release+shared=True
  - build_compiler-rt_3.8.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_4.0.0_clang60_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_clang60_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_clang60_build_type=Release+shared=True
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_4.0.0_gcc5_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc5_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_gcc5_build_type=Release+shared=True
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_libcxx_4.0.0_gcc7_build_type=Release+shared=True:
  dependencies:
  - build_llvm_4.0.0_gcc7_build_type=Release+shared=True
  - build_compiler-rt_4.0.0_gcc7_build_type=Release+shared=True
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    -o compiler-rt:shared=True -o libcxx:shared=True libcxx Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload libcxx/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: libcxx
  tags:
  - linux
  - docker
build_llvm_3.8.0_clang60_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_3.8.0_gcc5_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_3.8.0_gcc7_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=3.8.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/3.8.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_4.0.0_clang60_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conanclang60
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_4.0.0_gcc5_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conangcc5
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
build_llvm_4.0.0_gcc7_build_type=Release+shared=True:
  dependencies: []
  image: lasote/conangcc7
  script:
  - conan profile update settings.build_type=Release default
  - CONAN_VERSION_OVERRIDE=4.0.0 conan create --profile=default -o llvm:shared=True
    llvm Manu343726/testing
  - conan remove -b -s -f "*"
  - conan upload llvm/4.0.0@Manu343726/testing -r Manu343726 --all --force --retry
    3
  stage: llvm
  tags:
  - linux
  - docker
deploy-sources-to-bintray:
  image: lasote/conangcc5
  script:
  - ./get_jfrog.sh && ./jfrog bt config --interactive=false --user=Manu343726 --key=$manu343726_bintray_key
    --licenses="MIT"
  - export LLVM_URL=http://releases.llvm.org EXT=.src.tar.xz
  - export COMPONENT=llvm VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=llvm VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=compiler-rt VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=libcxx VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT $VERSION
    ${LLVM_URL}/${VERSION}/cfe-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=3.8.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=3.9.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=4.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=5.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  - export COMPONENT=clang-tools-extra VERSION=6.0.0 && ./llvm-sources.sh $COMPONENT
    $VERSION ${LLVM_URL}/${VERSION}/${COMPONENT}-${VERSION}${EXT}
  stage: sources
stages:
- common-recipe-scripts
- sources
- llvm
- compiler-rt
- libcxx
- clang
